### PR TITLE
Add the ability to send custom request headers for the ajax method

### PR DESCRIPTION
**Pull request by gorilonmax**
* Add `headers` field in the `shoestring.ajax.settings`.
* Update code to look for custom headers and include them in the `req` object.
* Add line to describe the new param in the NOTES section.

### CODE REVIEW

**Comment by jefflembeck** [comment]
:+1: I'd love to figure out a test for this first, but as soon as we do, I'm into this.

**Comment by JonathanPrince** [comment]
I used sinon.js in PR (#77) to test xhr, you could use that to test the request headers

**Comment by jefflembeck** [comment]
@JonathanPrince oh that's great - We're going to get yours in first, hopefully tomorrow, then figure out a test to bring this in.

**Comment by gorilonmax** [comment]
I'm really happy that you guys accepted my contribution. Thanks!

**Pull request merged**
